---
title: "BIA_results"
output:
  pdf_document: default
  html_document: default
---

```{r echo=FALSE, message=FALSE, warning=FALSE}

  library(epicR)
  library(tidyverse)
  library(dplyr)
  library(ggplot2)
  library(gridExtra)
  library(ggpubr)
  library(knitr)
  library(kableExtra)
  library(ggrepel)

```

```{r global settings, echo=FALSE}

  record_mode <- c(record_mode_none=0,
                   record_mode_agent=1,
                   record_mode_event=2,
                   record_mode_some_event=3)

  settings <- get_default_settings()
  settings$record_mode <- record_mode["record_mode_none"] 
  settings$n_base_agents <- 18162236 # change number of agents - 18mil=est Canadian pop >= 40, 1st Jan 2015      https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710000501
  settings$n_base_agents <- settings$n_base_agents - 1 
  settings$update_continuous_outcomes_mode <- 1
  settings$random_number_agent_refill <- 1

  

  # * common input values ---------------------------------------------------
  # these input values all remain constant across case detection scenarios
  time_horizon <- 13
  yrs_btw_CD <- 20 # ensures no individual tested twice
  CD_start_cal_year <- 2022
  CD_start_year <- CD_start_cal_year - 2015 # default is 50 i.e. no case detection
  CD_end_cal_year <- 2026
  CD_end_year <- CD_end_cal_year - 2015 # default is 50 i.e. no case detection
  discount_rate <- 0 # the default
  med_adherence <- 0.7 # the default, adjust for sensitivity analysis
  smoking_adherence <- 0 # the default, adjust for sensitivity analysis
  p_case_detection <- c(0.05,0.1,0.15,0.2,0.25) 
  p_correct_overdiagnosis <- 0.67 # did my own validation on this
  price_yr <- 1.030665381 # 2021 average ; was OG 1.03761 = Jan 2022 (so not very different but I think 2021 makes more sense)
  
  
  max_age <- 75 #85 #79 # default 111 - max age in EPIC
  
  
  # set buffer sizes
  settings$runif_buffer_size <- time_horizon*70 # ran for agents=100,000 & TH=13, max observed was 650
  settings$rexp_buffer_size <- time_horizon*140 # ran for agents=100,000 & TH=13, max observed was 1,300
  settings$rnorm_buffer_size <- time_horizon*8 + 10 # will equal 8*TH + 8, +2 for safety
  settings$rgamma_buffer_size <- time_horizon + 2 # will equal TH+1 at max, +1 for safety


```

```{r functions, echo=FALSE}

# * EPIC simulation ------------------------------------------------------------

  # CD_method : "None" "CDQ17" "CDQ195" "CDQ165" "FlowMeter" "FlowMeter_CDQ"
  # eligibility_criteria : "All patients" "Symptomatic" "Eversmokers"

  BIA_simul <- function(CD_method, eligibility_criteria){

    #CD_method <- "FlowMeter" ; eligibility_criteria <- "All patients"

    if(!CD_method %in% c("None", "CDQ17", "CDQ195", "CDQ165", "FlowMeter", "FlowMeter_CDQ")){
      print("Unknown case detection method")
    }

    ### run simulation
    init_session(settings=settings)
    input <- get_input()

    if(eligibility_criteria=="All patients"){
      min_age <- 40
      min_pack_years <- 0
      num_symptoms <- 0
      CD_values <- input$values$diagnosis$case_detection_methods[,CD_method]
    }else if (eligibility_criteria=="Symptomatic"){
      min_age <- 40
      min_pack_years <- 0
      num_symptoms <- 1
      CD_values <- input$values$diagnosis$case_detection_methods_symptomatic[,CD_method]
    }else if (eligibility_criteria=="Eversmokers"){
      min_age <- 50
      min_pack_years <- 0.001
      num_symptoms <- 0
      CD_values <- input$values$diagnosis$case_detection_methods_eversmokers[,CD_method]
    }else{
      terminate_session()
      return("Unknown eligibility criteria")
    }

    input$values$global_parameters$time_horizon <- time_horizon #time_horizon + (CD_start_year-2015) + 1
      input$values$diagnosis$case_detection_start_end_yrs <- c(CD_start_year, CD_end_year)
    #}
    input$values$diagnosis$years_btw_case_detection <- yrs_btw_CD
    input$values$global_parameters$discount_cost <- discount_rate
    input$values$medication$medication_adherence <- med_adherence
    input$values$smoking$smoking_cessation_adherence <- smoking_adherence
    if(CD_method!="None"){
    input$values$diagnosis$p_case_detection[(CD_start_year+1):(CD_start_year+length(p_case_detection))] <- p_case_detection
    }
    input$values$diagnosis$p_correct_overdiagnosis <- p_correct_overdiagnosis

    input$values$diagnosis$min_cd_age <- min_age
    input$values$diagnosis$max_cd_age <- max_age
    input$values$diagnosis$min_cd_pack_years <- min_pack_years
    input$values$diagnosis$min_cd_symptoms <- num_symptoms

    input$values$cost$cost_case_detection <- CD_values[3]*price_yr
    input$values$diagnosis$logit_p_prevalent_diagnosis_by_sex["case_detection.None",] <- CD_values[1]
    input$values$diagnosis$logit_p_diagnosis_by_sex["case_detection.None",] <- CD_values[1]
    input$values$diagnosis$logit_p_overdiagnosis_by_sex["case_detection.None",] <- CD_values[2]

    input$values$cost$bg_cost_by_stage <- input$values$cost$bg_cost_by_stage*price_yr
    input$values$cost$cost_smoking_cessation <- input$values$cost$cost_smoking_cessation*price_yr
    input$values$cost$exac_dcost <- input$values$cost$exac_dcost*price_yr
    input$values$cost$cost_outpatient_diagnosis <- input$values$cost$cost_outpatient_diagnosis*price_yr
    input$values$cost$cost_gp_visit <- input$values$cost$cost_gp_visit*price_yr
    input$values$medication$medication_costs <- input$values$medication$medication_costs*price_yr

    set.seed(445) #333
    run(input = input$values)

    output <- Cget_output()
    output_ex <- Cget_output_ex()

    terminate_session()


    # number alive
    base <- data.frame(year=1:(time_horizon),
                       criteria=eligibility_criteria,
                       CD_method=CD_method,
                       alive=rowSums(output_ex$n_alive_by_ctime_sex),
                       sex=output_ex$n_alive_by_ctime_sex[,2], # is this male or female???
                       smoke=output_ex$n_smoking_status_by_ctime[,2]
    )

    # number with COPD and diagnosed
    diags <- data.frame(copd=rowSums(output_ex$n_COPD_by_ctime_severity[,2:5]),
                        copd_sev=output_ex$n_COPD_by_ctime_severity[,4],
                        diags_true=rowSums(output_ex$n_Diagnosed_by_ctime_severity[,2:5]), # diagnosed here is true diagnosed only
                        diags_false=rowSums(output_ex$n_Overdiagnosed_by_ctime_sex),
                        diags_total=rowSums(output_ex$n_Diagnosed_by_ctime_severity[,2:5])+rowSums(output_ex$n_Overdiagnosed_by_ctime_sex)
    )

    # health outcomes
    healthOC <- data.frame(exacs=rowSums(output_ex$n_exac_by_ctime_severity),
                           exacs_mild=output_ex$n_exac_by_ctime_severity[,1],
                           exacs_mod=output_ex$n_exac_by_ctime_severity[,2],
                           exacs_sev=output_ex$n_exac_by_ctime_severity[,3],
                           exacs_vsev=output_ex$n_exac_by_ctime_severity[,4],
                           deaths=rowSums(output_ex$n_exac_death_by_ctime_severity),
                           NRT=output_ex$n_smoking_cessation_by_ctime)

    # number of case detections
    case_detection <- data.frame(case_detection=rowSums(output_ex$n_case_detection_by_ctime),
                                 CD_true_pos=output_ex$n_case_detection_by_ctime[,3],
                                 CD_false_pos=output_ex$n_case_detection_by_ctime[,2])

    # costs
    costs <- output_ex$annual_cost_ctime

    hosps <- output_ex$n_exac_by_ctime_severity[,3:4]
    hosps_cost <- input$values$cost$exac_dcost[3:4]
    hosps_cost_yr <- rowSums(t(c(hosps_cost)*t(hosps)))

    copd <- output_ex$cumul_time_by_ctime_GOLD[,2:5] #output_ex$n_COPD_by_ctime_severity[,2:5] # column 1 is gold grade 0 i.e. no copd
    main_cost <- input$values$cost$bg_cost_by_stage[2:5]
    copd_cost_yr <- rowSums(t(c(main_cost)*t(copd)))

    caseds <- output_ex$n_case_detection_by_ctime
    caseds_cost <- c(input$values$cost$cost_case_detection,
                     input$values$cost$cost_case_detection+input$values$cost$cost_outpatient_diagnosis,
                     input$values$cost$cost_case_detection+input$values$cost$cost_outpatient_diagnosis)
    caseds_cost_yr <- rowSums(t(c(caseds_cost)*t(caseds)))

    medyrs <- output_ex$medication_time_by_ctime_class[,1:4]
    medyrs_combos <- data.frame(SABA=medyrs[,1],
                                LAMA=medyrs[,3]-medyrs[,2],
                                LAMA_LABA=medyrs[,2]-medyrs[,4],
                                ICS_LAMA_LABA=medyrs[,4])
    meds_cost <- input$values$medication$medication_costs[c(2,5,7,15)]
    meds_cost_yr <- rowSums(t(c(meds_cost)*t(medyrs_combos))) + 
      output_ex$n_smoking_cessation_by_ctime*input$values$cost$cost_smoking_cessation

    costs_subcs <- data.frame(cost_total=costs,
                              cost_case_detection=caseds_cost_yr,
                              cost_treat=meds_cost_yr,
                              cost_hosp=hosps_cost_yr,
                              cost_maint=copd_cost_yr)

    results <- cbind(base,diags,healthOC,case_detection,costs_subcs)
    
    
    
    # overall results
    overall <- data.frame(n_agents=output_ex$n_agents_CD,
                          n_diagnosed=output_ex$n_diagnosed_true_CD,
                          n_CD_eligible=output_ex$n_case_detection_eligible)
    
    
    
    return(list(overall=overall,results=results))

    }
  



  # * BIA table - compare two scenarios -------------------------------------
  
  bia_table <- function(table,base_scenario,alt_scenario){
    
    base_table <- table %>%
      filter(scenario==base_scenario) %>%
      mutate(cost_case_detection_time=case_detection*11.91, .after=cost_case_detection) %>% 
      mutate(cost_case_detection_use=cost_case_detection-cost_case_detection_time, .after=cost_case_detection_time) %>% 
      select(year,scenario,criteria,CD_method,cost_total:cost_maint) %>% 
      mutate(cost_other=cost_total-cost_case_detection-cost_hosp-cost_treat)
      
    
    alt_table <- table %>%
      filter(scenario==alt_scenario) %>%
      mutate(cost_case_detection_time=case_detection*11.91, .after=cost_case_detection) %>% 
      mutate(cost_case_detection_use=cost_case_detection-cost_case_detection_time, .after=cost_case_detection_time) %>% 
      select(year,scenario,criteria,CD_method,cost_total:cost_maint) %>% 
      mutate(cost_other=cost_total-cost_case_detection-cost_hosp-cost_treat)
    
    bia_table <- data.frame(year=0:length(p_case_detection),
                            scenario=alt_scenario,
                            criteria=alt_table$criteria[1],
                            CD_method=alt_table$CD_method[1],
                            bia_total=base_table$cost_total-alt_table$cost_total,
                            bia_case_detection=base_table$cost_case_detection-alt_table$cost_case_detection,
                            bia_treat=base_table$cost_treat-alt_table$cost_treat,
                            bia_hosp=base_table$cost_hosp-alt_table$cost_hosp,
                            bia_maint=base_table$cost_maint-alt_table$cost_maint,
                            bia_other=base_table$cost_other-alt_table$cost_other)
    
    table <- bind_rows(
      base_table %>%
        pivot_longer(cols=cost_total:cost_other,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
      ,
      alt_table %>%
        pivot_longer(cols=cost_total:cost_other,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
      ,
      bia_table %>%
        pivot_longer(cols=bia_total:bia_other,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
    )
    
    return(table)
    
  }





  # * BIA per COPD patient table - compare two scenarios --------------------
  
  bia_table_pp <- function(table,base_scenario,alt_scenario){
    
    base_table <- table %>%
      filter(scenario==base_scenario) %>%
      select(year,scenario,criteria,CD_method,cost_total_pp:cost_maint_pp)
    
    alt_table <- table %>%
      filter(scenario==alt_scenario) %>%
      select(year,scenario,criteria,CD_method,cost_total_pp:cost_maint_pp)
    
    bia_table <- data.frame(year=0:length(p_case_detection),
                            scenario=alt_scenario,
                            criteria=alt_table$criteria[1],
                            CD_method=alt_table$CD_method[1],
                            bia_total_pp=base_table$cost_total_pp-alt_table$cost_total_pp,
                            bia_case_detection_pp=base_table$cost_case_detection_pp-alt_table$cost_case_detection_pp,
                            bia_treat_pp=base_table$cost_treat_pp-alt_table$cost_treat_pp,
                            bia_hosp_pp=base_table$cost_hosp_pp-alt_table$cost_hosp_pp,
                            bia_maint_pp=base_table$cost_maint_pp-alt_table$cost_maint_pp)
    
    table <- bind_rows(
      base_table %>%
        pivot_longer(cols=cost_total_pp:cost_maint_pp,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
      ,
      alt_table %>%
        pivot_longer(cols=cost_total_pp:cost_maint_pp,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
      ,
      bia_table %>%
        pivot_longer(cols=bia_total_pp:bia_maint_pp,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
    )
    
    return(table)
    
  }

```

```{r run simulations, echo=FALSE, message=FALSE}

  # * S1: All patients ------------------------------------------------------
  
  s10 <- BIA_simul(CD_method = "None", eligibility_criteria = "All patients")
  saveRDS(s10,"s10.Rda")
  s1a <- BIA_simul(CD_method = "CDQ17", eligibility_criteria = "All patients")
  saveRDS(s1a,"s1a.Rda")
  s1b <- BIA_simul(CD_method = "FlowMeter", eligibility_criteria = "All patients")
  saveRDS(s1b,"s1b.Rda")
  s1c <- BIA_simul(CD_method = "FlowMeter_CDQ", eligibility_criteria = "All patients")
  saveRDS(s1c,"s1c.Rda")

  
  # * S2: Symptomatic patients ----------------------------------------------
  
  s2a <- BIA_simul(CD_method = "FlowMeter", eligibility_criteria = "Symptomatic")
  saveRDS(s2a,"s2a.Rda")

  
  # * S3: Eversmokers + age >= 50 -------------------------------------------
  
  s3a <- BIA_simul(CD_method = "CDQ195", eligibility_criteria = "Eversmokers")
  saveRDS(s3a,"s3a.Rda")
  s3b <- BIA_simul(CD_method = "CDQ165", eligibility_criteria = "Eversmokers")
  saveRDS(s3b,"s3b.Rda")
  s3c <- BIA_simul(CD_method = "FlowMeter", eligibility_criteria = "Eversmokers")
  saveRDS(s3c,"s3c.Rda")
  s3d <- BIA_simul(CD_method = "FlowMeter_CDQ", eligibility_criteria = "Eversmokers")
  saveRDS(s3d,"s3d.Rda")

  
  # save all results
  all_s <- list(s10=s10,s1a=s1a,s1b=s1b,s1c=s1c,s2a=s2a,s3a=s3a,s3b=s3b,s3c=s3c,s3d=s3d)
  #saveRDS(all_s, "results_maxage445_resubmit.Rda")
  

```

```{r load and prepare data, echo=FALSE}

# Read in data ------------------------------------------------------------
  
  alldat <- readRDS("results_base445_resubmit.Rda")
  #alldat <- all_s
  
# * prepare data ----------------------------------------------------------

  # overall output
  s10o <- alldat$s10$overall %>% mutate(scenario="s10") %>% relocate(scenario)
  s1ao <- alldat$s1a$overall %>% mutate(scenario="s1a") %>% relocate(scenario)
  s1bo <- alldat$s1b$overall %>% mutate(scenario="s1b") %>% relocate(scenario)
  s1co <- alldat$s1c$overall %>% mutate(scenario="s1c") %>% relocate(scenario)
  s2ao <- alldat$s2a$overall %>% mutate(scenario="s2a") %>% relocate(scenario)
  s3ao <- alldat$s3a$overall %>% mutate(scenario="s3a") %>% relocate(scenario)
  s3bo <- alldat$s3b$overall %>% mutate(scenario="s3b") %>% relocate(scenario)
  s3co <- alldat$s3c$overall %>% mutate(scenario="s3c") %>% relocate(scenario)
  s3do <- alldat$s3d$overall %>% mutate(scenario="s3d") %>% relocate(scenario)
  
  all_overall <- bind_rows(s10o,s1ao,s1bo,s1co,s2ao,s3ao,s3bo,s3co,s3do) # combine
  
  
  
  # set baseline year and case detection years
  baseline_yr <- CD_start_year+1-1
  CD_yrs <- (CD_start_year+1):(CD_start_year+length(p_case_detection))
  
  # year-by-year results
  s10 <- alldat$s10$results %>% mutate(scenario="s10", .after=year)
  s1a <- alldat$s1a$results %>% mutate(scenario="s1a", .after=year)
  s1b <- alldat$s1b$results %>% mutate(scenario="s1b", .after=year)
  s1c <- alldat$s1c$results %>% mutate(scenario="s1c", .after=year)
  
  s2a <- alldat$s2a$results %>% mutate(scenario="s2a", .after=year)
  
  s3a <- alldat$s3a$results %>% mutate(scenario="s3a", .after=year)
  s3b <- alldat$s3b$results %>% mutate(scenario="s3b", .after=year)
  s3c <- alldat$s3c$results %>% mutate(scenario="s3c", .after=year)
  s3d <- alldat$s3d$results %>% mutate(scenario="s3d", .after=year)
  
  
  # combine all year-by-year results
  all_results <- bind_rows(s10,s1a,s1b,s1c,s2a,s3a,s3b,s3c,s3d) %>% 
    filter(year %in% c(baseline_yr,CD_yrs)) %>% # remove unnecessary data
    mutate(year=year-baseline_yr) %>% # renumber so baseline year = 0 then 1:5 case detection years
    mutate(copd_prev=copd/alive*100, .after=copd) %>%
    mutate(diags_true_prev=diags_true/alive*100, .after=diags_true) %>%
    mutate(diags_false_prev=diags_false/(alive-copd)*100, .after=diags_false) %>%
    mutate(diags_total_prev=diags_total/alive*100, .after=diags_total) %>%
    mutate(cost_total_pp=cost_total/alive) %>%
    mutate(cost_case_detection_pp=cost_case_detection/alive) %>%
    mutate(cost_treat_pp=cost_treat/alive) %>%
    mutate(cost_hosp_pp=cost_hosp/alive) %>%
    mutate(cost_maint_pp=cost_maint/alive)


```

```{r baseline year, echo=FALSE}


# * compare baseline years ------------------------------------------------

baseline_compar_raw <- all_results %>%
  filter(year==0) %>% 
  select(-year)

baseline_compar_percent <- baseline_compar_raw %>%
  mutate(across(alive:cost_maint_pp, function(x) (x - mean(x))/mean(x)*100)) 


baseline_avg <- baseline_compar_raw %>% 
  summarize(alive=mean(alive),
            sex=mean(sex),
            smoke=mean(smoke),
            copd=mean(copd),
            copd_prev=mean(copd_prev),
            #copd_sev=mean(copd_sev),
            diags_true=mean(diags_true),
            diags_true_prev=mean(diags_true_prev),
            diags_false=mean(diags_false),
            diags_false_prev=mean(diags_false_prev),
            diags_total=mean(diags_total),
            diags_total_prev=mean(diags_total_prev),
            exacs=mean(exacs),
            exacs_mild=mean(exacs_mild),
            exacs_mod=mean(exacs_mod),
            exacs_sev=mean(exacs_sev),
            exacs_vsev=mean(exacs_vsev),
            deaths=mean(deaths),
            NRT=mean(NRT),
            case_detection=0,
            CD_true_pos=0,
            CD_false_pos=0,
            cost_total=mean(cost_total),
            cost_case_detection=0,
            cost_treat=mean(cost_treat),
            cost_hosp=mean(cost_hosp),
            cost_maint=mean(cost_maint),
            cost_total_pp=mean(cost_total_pp),
            cost_case_detection_pp=0,
            cost_treat_pp=mean(cost_treat_pp),
            cost_hosp_pp=mean(cost_hosp_pp),
            cost_maint_pp=mean(cost_maint_pp)
            )


  # insert baseline average into data set
  #all_results[which(all_results$year==0),5:36] <- baseline_avg


baseline_compar_raw
baseline_compar_percent
baseline_avg
  

```

```{r overall results, echo=FALSE}


# number eligible / tested / true positives / false positives
overall <- all_overall %>% 
  inner_join(
    all_results %>% 
      #filter(year>0) %>% 
      group_by(scenario) %>% 
      summarize(case_detection=sum(case_detection),
                true_positive=sum(CD_true_pos),
                false_positive=sum(CD_false_pos),
                exacs=sum(exacs)),
    by="scenario"
  ) %>% 
  mutate(percent_pop_CD=case_detection/n_agents*100, .after=case_detection) %>% 
  mutate(percent_eligible_CD=case_detection/n_CD_eligible*100, .after=percent_pop_CD) %>%   
  mutate(percent_eligible=n_CD_eligible/n_agents*100, .after=n_CD_eligible) %>% 
  mutate(true_positive_rate=true_positive/case_detection*100, .after=true_positive) %>% 
  mutate(false_positive_rate=false_positive/case_detection*100, .after=false_positive)

overall


```

```{r BIA results, echo=FALSE, message=FALSE, warning=FALSE}


# run budget impact function
bia_s10_s1a <- bia_table(all_results,"s10","s1a")
bia_s10_s1b <- bia_table(all_results,"s10","s1b")
bia_s10_s1c <- bia_table(all_results,"s10","s1c")
bia_s10_s2a <- bia_table(all_results,"s10","s2a")
bia_s10_s3a <- bia_table(all_results,"s10","s3a")
bia_s10_s3b <- bia_table(all_results,"s10","s3b")
bia_s10_s3c <- bia_table(all_results,"s10","s3c")
bia_s10_s3d <- bia_table(all_results,"s10","s3d")


bia_all_long <- bind_rows(bia_s10_s1a,
                          bia_s10_s1b,
                          bia_s10_s1c,
                          bia_s10_s2a,
                          bia_s10_s3a,
                          bia_s10_s3b,
                          bia_s10_s3c,
                          bia_s10_s3d) %>% 
  distinct() %>% 
  pivot_longer(cols=year_0:year_5,names_to="year",values_to="CAD") %>% 
  mutate(year=fct_recode(year,"2021"="year_0","2022"="year_1","2023"="year_2","2024"="year_3","2025"="year_4","2026"="year_5")) %>% 
  mutate(scenario=fct_recode(scenario,"S10"="s10","S1a"="s1a","S1b"="s1b","S1c"="s1c","S2a"="s2a","S3a"="s3a","S3b"="s3b","S3c"="s3c","S3d"="s3d")) %>% 
  mutate(year=as.numeric(year)+2020) %>% 
  mutate(label=if_else(year==max(year),as.character(scenario),NA_character_))




# total cost and BI over time horizon - used to produce table 4 of main article
bia_total <- bia_all_long %>% 
  filter(year!="2021") %>% 
  group_by(scenario,cost_group) %>% 
  summarize(total_CAD=sum(CAD)) %>% 
  pivot_wider(names_from=scenario,values_from=total_CAD) 




# cost plots. NOTE: these are costs not budget impact; these were not used in the final paper
p1 <- ggplot(bia_all_long %>% filter(cost_group=="cost_total"),
             aes(x=year,y=CAD/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Total cost (million $)") + xlab("Year") +
    geom_point() +
  geom_line() +
  theme_bw() +
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2),
        legend.position = "none") 

p2 <- ggplot(bia_all_long %>% filter(cost_group=="cost_case_detection"),
             aes(x=year,y=CAD/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Case detection cost (million $)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw() + 
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2)) + 
  guides(colour = guide_legend(nrow = 1)) 

p3 <- ggplot(bia_all_long %>% filter(cost_group=="cost_treat"),
             aes(x=year,y=CAD/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Treatment cost (million $)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw() +
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2)) + 
  guides(colour = guide_legend(nrow = 1)) 

p4 <- ggplot(bia_all_long %>% filter(cost_group=="cost_hosp"),
             aes(x=year,y=CAD/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Hospitalization cost (million $)") + xlab("Year") +
  geom_point() +
  geom_line() +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey") +
  theme_bw() + 
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2)) + 
  guides(colour = guide_legend(nrow = 1)) 

p5 <- ggplot(bia_all_long %>% filter(cost_group=="cost_other"),
             aes(x=year,y=CAD/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Outpatient care cost (million $)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw() + 
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2)) + 
  guides(colour = guide_legend(nrow = 1)) 




# budget impact plots plots
p6 <- ggplot(bia_all_long %>% filter(cost_group=="bia_total" & scenario!="s10"),
             aes(x=year,y=CAD*(-1)/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_x_continuous(expand=c(0.01,0.01),limits=c(2021,2026.2)) +
  scale_y_continuous(breaks=seq(0,140,25),expand=c(0.02,0.02),limits=c(0,131)) +
  ylab("Total costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  theme_bw() +
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2),
        legend.position = "none") +
  geom_text_repel(aes(label=label),
                  nudge_x=0.2,
                  min.segment.length=Inf,
                  direction="y")

p7 <- ggplot(bia_all_long %>% filter(cost_group=="bia_case_detection" & scenario!="s10"),
             aes(x=year,y=CAD*(-1)/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_x_continuous(expand=c(0.01,0.01),limits=c(2021,2026.5)) +
  scale_y_continuous(breaks=seq(0,140,25),expand=c(0.02,0.02),limits=c(0,131)) +
  ylab("Case detection costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  theme_bw() + 
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2),
        legend.position = "none") +
  guides(colour = guide_legend(nrow = 1)) +
  geom_text_repel(aes(label=label),
                  nudge_x=0.3,
                  min.segment.length=Inf,
                  #box.padding=0.1,
                  #force=0.05,
                  direction = "y")

p8 <- ggplot(bia_all_long %>% filter(cost_group=="bia_treat" & scenario!="s10"),
             aes(x=year,y=CAD*(-1)/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_x_continuous(expand=c(0.01,0.01),limits=c(2021,2026.5)) +
  scale_y_continuous(expand=c(0.02,0.02)) +
  ylab("Treatment costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  theme_bw() +
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2),
        legend.position = "none") +
  guides(colour = guide_legend(nrow = 1)) +
  geom_text_repel(aes(label=label),
                  nudge_x=0.3,
                  min.segment.length=Inf,
                  direction="y")

p9 <- ggplot(bia_all_long %>% filter(cost_group=="bia_hosp" & scenario!="s10"),
             aes(x=year,y=CAD*(-1)/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_x_continuous(expand=c(0.01,0.01),limits=c(2021,2026.5)) +
  scale_y_continuous(expand=c(0.02,0.02)) +
  ylab("Hospitalisation costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey") +
  theme_bw() + 
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2),
        legend.position = "none") +
  guides(colour = guide_legend(nrow = 1)) +
  geom_text_repel(aes(label=label),
                  nudge_x=0.3,
                  min.segment.length=Inf,
                  #box.padding=0.05,
                  #force=0.1,
                  #force_pull=0.3,
                  direction="y")

p10 <- ggplot(bia_all_long %>% filter(cost_group=="bia_other" & scenario!="s10"),
              aes(x=year,y=CAD*(-1)/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_x_continuous(expand=c(0.01,0.01),limits=c(2021,2026.5)) +
  scale_y_continuous(expand=c(0.02,0.02)) +
  ylab("Outpatient care costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  theme_bw() + 
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2),
        legend.position = "none") +
  guides(colour = guide_legend(nrow = 1)) +
  geom_text_repel(aes(label=label),
                  nudge_x=0.3,
                  min.segment.length=Inf,
                  direction="y")




# print results

# total budget impact table (table 4 of main article)
bia_total 

# total costs combined plot (not used in main article)
ggarrange(p1,
          ggarrange(p2,p3,p4,p5,ncol=2,nrow=2,common.legend=TRUE,legend="bottom"),
          nrow=2
)


# budget impact combined plot (figure 2 of main article)

ggarrange(p6,
          ggarrange(p7,p8,p9,p10,ncol=2,nrow=2),
          nrow=2
)

ggsave("base_resubmit.tiff",width=6000,height=8400,units="px",dpi=600)


```













```{r ISPOR plots, echo=FALSE, message=FALSE, warning=FALSE}


# run budget impact function
bia_s10_s1a <- bia_table(all_results,"s10","s1a")
bia_s10_s1b <- bia_table(all_results,"s10","s1b")
bia_s10_s1c <- bia_table(all_results,"s10","s1c")
bia_s10_s2a <- bia_table(all_results,"s10","s2a")
bia_s10_s3a <- bia_table(all_results,"s10","s3a")
bia_s10_s3b <- bia_table(all_results,"s10","s3b")
bia_s10_s3c <- bia_table(all_results,"s10","s3c")
bia_s10_s3d <- bia_table(all_results,"s10","s3d")


bia_all_long <- bind_rows(bia_s10_s1a,
                          bia_s10_s1b,
                          bia_s10_s1c,
                          bia_s10_s2a,
                          bia_s10_s3a,
                          bia_s10_s3b,
                          bia_s10_s3c,
                          bia_s10_s3d) %>% 
  distinct() %>% 
  pivot_longer(cols=year_0:year_5,names_to="year",values_to="CAD") %>% 
  mutate(year=fct_recode(year,"2021"="year_0","2022"="year_1","2023"="year_2","2024"="year_3","2025"="year_4","2026"="year_5")) %>% 
  mutate(scenario=fct_recode(scenario,"S10"="s10","S1a"="s1a","S1b"="s1b","S1c"="s1c","S2a"="s2a","S3a"="s3a","S3b"="s3b","S3c"="s3c","S3d"="s3d")) %>% 
  mutate(year=as.numeric(year)+2020) %>% 
  mutate(label=if_else(year==max(year),as.character(scenario),NA_character_))



# cost plots
p1 <- ggplot(bia_all_long %>% filter(cost_group=="cost_total"),
             aes(x=year,y=CAD/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Total cost (million $)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()
p2 <- ggplot(bia_all_long %>% filter(cost_group=="cost_case_detection"),
             aes(x=year,y=CAD/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Case detection cost (million $)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()
p3 <- ggplot(bia_all_long %>% filter(cost_group=="cost_treat"),
             aes(x=year,y=CAD/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Treatment cost (million $)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()
p4 <- ggplot(bia_all_long %>% filter(cost_group=="cost_hosp"),
             aes(x=year,y=CAD/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Hospitalization cost (million $)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()




# bia plots
p5 <- ggplot(bia_all_long %>% filter(cost_group=="bia_total" & scenario!="s10"),
             aes(x=year,y=CAD*(-1)/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_x_continuous(expand=c(0.01,0.01)) +
  ylab("Additional costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  scale_y_continuous(breaks=seq(0,140,25),expand=c(0.02,0.02),limits=c(0,131)) +
  theme_bw() +
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2)) + 
  guides(colour = guide_legend(nrow = 1)) +
  annotate("label", x=2021.3, y = 126, label = "Total", size=6) 
p6 <- ggplot(bia_all_long %>% filter(cost_group=="bia_case_detection" & scenario!="s10"),
             aes(x=year,y=CAD*(-1)/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_x_continuous(expand=c(0.01,0.01)) +
  scale_y_continuous(breaks=seq(0,140,25),expand=c(0.02,0.02),limits=c(0,131)) +
  ylab("Additional costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  theme_bw() + 
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2)) + 
  guides(colour = guide_legend(nrow = 1)) +
  annotate("label", x = 2021.85, y = 126, label = "Case detection", size=6) 
p7 <- ggplot(bia_all_long %>% filter(cost_group=="bia_treat" & scenario!="s10"),
             aes(x=year,y=CAD*(-1)/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_x_continuous(expand=c(0.01,0.01)) +
  scale_y_continuous(expand=c(0.02,0.02)) +
  ylab("Additional costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  theme_bw() +
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2)) + 
  guides(colour = guide_legend(nrow = 1)) +
  annotate("label", x = 2021.6, y = 30, label = "Treatment", size=6) 
p8 <- ggplot(bia_all_long %>% filter(cost_group=="bia_hosp" & scenario!="s10"),
             aes(x=year,y=CAD*(-1)/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_x_continuous(expand=c(0.01,0.01)) +
  scale_y_continuous(expand=c(0.02,0.02)) +
  ylab("Additional costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  geom_hline(yintercept=0, linetype="dashed", color = "darkgrey") +
  theme_bw() + 
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2)) + 
  guides(colour = guide_legend(nrow = 1)) +
  annotate("label", x = 2021.8, y = 1.95, label = "Hospitalization", size=6) 
p9 <- ggplot(bia_all_long %>% filter(cost_group=="bia_other" & scenario!="s10"),
             aes(x=year,y=CAD*(-1)/1000000,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_x_continuous(expand=c(0.01,0.01)) +
  scale_y_continuous(expand=c(0.02,0.02)) +
  ylab("Outpatient care costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  theme_bw() + 
  guides(colour = guide_legend(nrow = 1)) +
  annotate("label", x = 2021.5, y = 125, label = "Outpatient", size=5) 




# total cost and BI over time horizon
bia_total <- bia_all_long %>% 
  filter(year!="2021") %>% 
  group_by(scenario,cost_group) %>% 
  summarize(total_CAD=sum(CAD)) %>% 
  pivot_wider(names_from=scenario,values_from=total_CAD) 


cost_increase_percent <- bia_total %>% 
  filter(cost_group=="bia_total") %>% 
  select(-S10,-cost_group) %>% 
  pivot_longer(cols=S1a:S3d,names_to="scenario",values_to="bia") %>% 
  mutate(cost_increase=-bia/bia_total$S10[which(bia_total$cost_group=="cost_total")]*100) %>% 
  mutate(percent_of_HC_budget=-bia/308000000000*100)



ggarrange(p1,p2,p3,p4,ncol=2,nrow=2,common.legend=TRUE,legend="bottom")

ggarrange(p5,p6,p7,p8,ncol=2,nrow=2,common.legend=TRUE,legend="bottom")
#ggsave("test.tiff",width=7000,height=5000,units="px",dpi=600)

ggarrange(p5,
          ggarrange(p6,p7,p8,p9,ncol=2,nrow=2,common.legend=TRUE,legend="bottom"),
          nrow=2
)



bia_s10_s1a
bia_s10_s1b %>% mutate(across(year_0:year_5, round, 0)) %>% slice(2,3,4,5,6,1,8,9,10,11,12,7,14,15,16,17,18,13) %>% select(4:10) %>% filter(cost_group!="cost_maint")
cbind(bia_total[,1],round(bia_total[,-1]/1000000))
cost_increase_percent


# aa <- data.frame(cost_group=c("No case detection strategy costs","Case detection strategy costs","Budget impact"), year_0=rep(0,3),year_1=rep(0,3),year_2=rep(0,3),year_3=rep(0,3),year_4=rep(0,3),year_5=rep(0,3))
# a <- bia_s10_s3d %>% mutate(across(year_0:year_5, round, 0)) %>% 
#   select(4:10) %>% filter(cost_group!="cost_maint" & cost_group!="bia_maint") %>% 
#   mutate(cost_group=fct_recode(cost_group,"Total"="cost_total","Case detection"="cost_case_detection","Treatment"="cost_treat","Outpatient"="cost_other","Hospitalisation"="cost_hosp",
#                          "Total"="bia_total","Case detection"="bia_case_detection","Treatment"="bia_treat","Outpatient"="bia_other","Hospitalisation"="bia_hosp")) %>% 
#   bind_rows(aa) %>% slice(16,2,3,4,5,1,17,7,8,9,10,6,18,12,13,14,15,11) %>% mutate(across(-1, prettyNum, big.mark=",", scientific=FALSE))
# names(a) <- c("Outcome","Baseline (2021)","2022","2023","2024","2025","2026")
# write.table(a, file = "testtab.txt", sep = ".", quote = FALSE, row.names = F)


#rowSums((abs(bia_total[7,-c(1,2)])/colSums(abs(bia_total[c(7,8,10,12),-c(1,2)]))*100))/8


```

```{r BIA per person results, echo=FALSE, message=FALSE, warning=FALSE}



# * budget impact per person ------------------------------------------


# run budget impact function
bia_pp_s10_s1a <- bia_table_pp(all_results,"s10","s1a")
bia_pp_s10_s1b <- bia_table_pp(all_results,"s10","s1b")
bia_pp_s10_s1c <- bia_table_pp(all_results,"s10","s1c")
bia_pp_s10_s2a <- bia_table_pp(all_results,"s10","s2a")
bia_pp_s10_s3a <- bia_table_pp(all_results,"s10","s3a")
bia_pp_s10_s3b <- bia_table_pp(all_results,"s10","s3b")
bia_pp_s10_s3c <- bia_table_pp(all_results,"s10","s3c")
bia_pp_s10_s3d <- bia_table_pp(all_results,"s10","s3d")


bia_pp_all_long <- bind_rows(bia_pp_s10_s1a,
                             bia_pp_s10_s1b,
                             bia_pp_s10_s1c,
                             bia_pp_s10_s2a,
                             bia_pp_s10_s3a,
                             bia_pp_s10_s3b,
                             bia_pp_s10_s3c,
                             bia_pp_s10_s3d) %>% 
  pivot_longer(cols=year_0:year_5,names_to="year",values_to="CAD") %>% 
  # mutate(year=fct_recode(year,"2021"="year_0","2022"="year_1","2023"="year_2","2024"="year_3","2025"="year_4","2026"="year_5",
  #                        "2027"="year_6","2028"="year_7","2029"="year_8","2030"="year_9","2031"="year_10")) %>% 
  # mutate(year=factor(year,levels=c("2021","2022","2023","2024","2025","2026","2027","2028","2029","2030","2031")))
  mutate(year=fct_recode(year,"2021"="year_0","2022"="year_1","2023"="year_2","2024"="year_3","2025"="year_4","2026"="year_5"))





# cost plots
p1 <- ggplot(bia_pp_all_long %>% filter(cost_group=="cost_total_pp"),
             aes(x=year,y=CAD,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Total cost per patient (CAD)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()
p2 <- ggplot(bia_pp_all_long %>% filter(cost_group=="cost_case_detection_pp"),
             aes(x=year,y=CAD,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Case detection cost per patient (CAD)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()
p3 <- ggplot(bia_pp_all_long %>% filter(cost_group=="cost_treat_pp"),
             aes(x=year,y=CAD,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Medication cost per patient (CAD)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()
p4 <- ggplot(bia_pp_all_long %>% filter(cost_group=="cost_hosp_pp"),
             aes(x=year,y=CAD,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Hospitalization cost per patient (CAD)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()






# bia plots
p5 <- ggplot(bia_pp_all_long %>% filter(cost_group=="bia_total_pp" & scenario!="s10"),
             aes(x=year,y=CAD*(-1),group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Total budget impact per patient (CAD)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()
p6 <- ggplot(bia_pp_all_long %>% filter(cost_group=="bia_case_detection_pp" & scenario!="s10"),
             aes(x=year,y=CAD*(-1),group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Case detection budget impact per patient (CAD)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()
p7 <- ggplot(bia_pp_all_long %>% filter(cost_group=="bia_treat_pp" & scenario!="s10"),
             aes(x=year,y=CAD*(-1),group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Medication budget impact per patient (CAD)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()
p8 <- ggplot(bia_pp_all_long %>% filter(cost_group=="bia_hosp_pp" & scenario!="s10"),
             aes(x=year,y=CAD*(-1),group=scenario,col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Hospitalization budget impact per patient (CAD)") + xlab("Year") +
  geom_point() +
  geom_line() +
  theme_bw()




# total cost and BI over time horizon
bia_pp_total <- bia_pp_all_long %>% 
  filter(year!="2021") %>% 
  group_by(scenario,cost_group) %>% 
  summarize(total_CAD=sum(CAD)) %>% 
  pivot_wider(names_from=scenario,values_from=total_CAD)




grid.arrange(p1,p2,p3,p4,nrow=2,common.legend=TRUE,legend="bottom")
grid.arrange(p5,p6,p7,p8,nrow=2,common.legend=TRUE,legend="bottom")
bia_pp_s10_s1a
bia_pp_total




```

```{r health outcomes results, echo=FALSE}

# * health outcomes results -----------------------------------------------


all_results_ho <- all_results %>%
  select(year,scenario,criteria,CD_method,alive,copd,copd_sev,diags_true,diags_false,exacs,exacs_mild,exacs_mod,exacs_sev,exacs_vsev,deaths) %>%
  mutate(overd_prev=diags_false/(alive-copd)*100,.after=diags_false) %>% 
  pivot_longer(cols=alive:deaths,names_to="ho_group",values_to="count") %>%
  pivot_wider(names_from=year,names_prefix="year_",values_from=count)

all_results_ho_long <- all_results_ho %>%
  pivot_longer(cols=year_0:year_5,names_to="year",values_to="count") %>% 
  mutate(year=fct_recode(year,"2021"="year_0","2022"="year_1","2023"="year_2","2024"="year_3","2025"="year_4","2026"="year_5")) %>% 
  mutate(year=as.numeric(year)+2020)




p1 <- ggplot(all_results_ho_long %>% filter(ho_group=="copd_sev"),
             aes(x=year,y=count,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Severe COPD") +
  geom_point() +
  geom_line() +
  theme_bw()
p2 <- ggplot(all_results_ho_long %>% filter(ho_group=="diags_true"),
             aes(x=year,y=count,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("True COPD diagnoses") +
  geom_point() +
  geom_line() +
  theme_bw()
p3 <- ggplot(all_results_ho_long %>% filter(ho_group=="diags_false"),
             aes(x=year,y=count,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Overdiagnosis") +
  geom_point() +
  geom_line() +
  theme_bw()
p4 <- ggplot(all_results_ho_long %>% filter(ho_group=="exacs"),
             aes(x=year,y=count,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Total exacerbations") +
  geom_point() +
  geom_line() +
  theme_bw()
p5 <- ggplot(all_results_ho_long %>% filter(ho_group=="exacs_mild"),
             aes(x=year,y=count,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Mild exacerbations") +
  geom_point() +
  geom_line() +
  theme_bw()
p6 <- ggplot(all_results_ho_long %>% filter(ho_group=="exacs_mod"),
             aes(x=year,y=count,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Moderate exacerbations") +
  geom_point() +
  geom_line() +
  theme_bw()
p7 <- ggplot(all_results_ho_long %>% filter(ho_group=="exacs_sev"),
             aes(x=year,y=count,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Severe exacerbations") +
  geom_point() +
  geom_line() +
  theme_bw()
p8 <- ggplot(all_results_ho_long %>% filter(ho_group=="exacs_vsev"),
             aes(x=year,y=count,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("very severe exacerbations") +
  geom_point() +
  geom_line() +
  theme_bw()
p9 <- ggplot(all_results_ho_long %>% filter(ho_group=="deaths"),
             aes(x=year,y=count,group=scenario,col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Deaths") +
  geom_point() +
  geom_line() +
  theme_bw()


grid.arrange(p2,p3,nrow=2)
grid.arrange(p5,p6,p7,p4,nrow=2)





ggplot(all_results_ho_long %>% filter(ho_group=="exacs" & (scenario=="s10" | scenario=="s1a")),
             aes(x=year,y=count,group=scenario,fill=scenario)) +
  #scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Total exacerbations") +
  geom_bar(stat = "identity", position=position_dodge()) +
  theme_bw()


all_results_ho_long %>%  filter(scenario=="s10" | scenario=="s1a") %>% 
       filter(grepl('exac', ho_group)) %>% 
       select(-criteria) %>% select(-CD_method) %>% 
       pivot_wider(names_from=scenario, values_from=count) %>% 
       mutate(diff=s10-s1a) %>% 
       select(-s10) %>% select(-s1a) %>% 
       pivot_wider(names_from=ho_group,values_from=diff) %>% 
       filter(year!="2021")


# total baseline exacs = 13,324,154
# total s1a exacs = 13,114,074
# difference = 210,080
# percentage change = 1.6% decrease


# over diagnosis plot

ggplot(all_results_ho_long %>% 
         mutate(group=case_when(scenario=="s10" ~ "S0",
                                criteria=="All patients" ~ "S1",
                                criteria=="Symptomatic" ~ "S2",
                                criteria=="Eversmokers" ~ "S3")) %>% 
         filter(ho_group=="overd_prev") %>% 
         group_by(group,year) %>% 
         summarize(count=mean(count)),
             aes(x=year,y=count,group=group,col=group)) +
 scale_color_manual(values=c("#808080", "#F5594E", "#00C0B8", "#BF80FF"),name="") +
  scale_x_continuous(expand=c(0.01,0.01),limits=c(2021,2026)) +
  scale_y_continuous(expand=c(0.02,0.02)) +
  ylab("Overdiagnosed prevalence (%)") + xlab("") +
  geom_point() +
  geom_line() +
  theme_bw() +
  theme(axis.text=element_text(size=12),axis.title=element_text(size=14),
        legend.text=element_text(size=12),legend.title=element_text(size=12),
        plot.margin = margin(2, 10, 0, 2)) 

#ggsave("overdiag.tiff",width=6000,height=4000,units="px",dpi=600)

```
