---
title: "Sensitivity analysis"
output: html_document
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}

  library(epicR)
  library(tidyverse)
  library(dplyr)
  library(ggplot2)
  library(gridExtra)
  library(ggpubr)
  library(ggrepel)
  library(knitr)
  library(kableExtra)

```


```{r global settings, echo=FALSE}

  record_mode <- c(record_mode_none=0,
                   record_mode_agent=1,
                   record_mode_event=2,
                   record_mode_some_event=3)

  settings <- get_default_settings()
  settings$record_mode <- record_mode["record_mode_none"] # stores the events matrix, switch to "record_mode_none" for faster code
  settings$n_base_agents <- 18162236 #18e+6 # change number of agents - 18mil=est Canadian pop >= 40, 1st Jan 2015      https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710000501
  settings$n_base_agents <- settings$n_base_agents - 1 # since it starts at id=0 ; ask Amin about this
  settings$update_continuous_outcomes_mode <- 1
  settings$random_number_agent_refill <- 1

  

  # * common input values ---------------------------------------------------
  # these input values all remain constant across case detection scenarios
  time_horizon <- 13 
  yrs_btw_CD <- 5 # ensures no individual tested twice
  CD_start_cal_year <- 2022
  CD_start_year <- CD_start_cal_year - 2015 # default is 50 i.e. no case detection
  discount_rate <- 0 # the default
  med_adherence <- 0.7 # the default, adjust for sensitivity analysis
  smoking_adherence <- 0.7 # the default, adjust for sensitivity analysis
  p_case_detection <- c(0.05,0.1,0.15,0.2,0.25) #c(0.1,0.15,0.2,0.25,0.3,0.3,0.3,0.3,0.3,0.3)
  p_correct_overdiagnosis <- 0.67 # did my own validation on this
  price_yr <- 1.030665381 # 2021 average ; was OG 1.03761 = Jan 2022 (so not very different but I think 2021 makes more sense)
  
  
  
  # set buffer sizes
  settings$runif_buffer_size <- time_horizon*70 # ran for agents=100,000 & TH=13, max observed was 650
  settings$rexp_buffer_size <- time_horizon*140 # ran for agents=100,000 & TH=13, max observed was 1,300
  settings$rnorm_buffer_size <- time_horizon*8 + 10 # will equal 8*TH + 8, +2 for safety
  settings$rgamma_buffer_size <- time_horizon + 2 # will equal TH+1 at max, +1 for safety


```


```{r BIA table, echo=FALSE}

# * EPIC simulation ------------------------------------------------------------

  # CD_method : "None" "CDQ17" "CDQ195" "CDQ165" "FlowMeter" "FlowMeter_CDQ"
  # eligibility_criteria : "All patients" "Symptomatic" "Eversmokers"

  BIA_simul <- function(CD_method, eligibility_criteria){

    #CD_method <- "FlowMeter" ; eligibility_criteria <- "All patients"

    if(!CD_method %in% c("None", "CDQ17", "CDQ195", "CDQ165", "FlowMeter", "FlowMeter_CDQ")){
      print("Unknown case detection method")
    }

    ### run simulation
    init_session(settings=settings)
    input <- get_input()

    if(eligibility_criteria=="All patients"){
      min_age <- 40
      min_pack_years <- 0
      num_symptoms <- 0
      CD_values <- input$values$diagnosis$case_detection_methods[,CD_method]
    }else if (eligibility_criteria=="Symptomatic"){
      min_age <- 40
      min_pack_years <- 0
      num_symptoms <- 1
      CD_values <- input$values$diagnosis$case_detection_methods_symptomatic[,CD_method]
    }else if (eligibility_criteria=="Eversmokers"){
      min_age <- 50
      min_pack_years <- 0.001
      num_symptoms <- 0
      CD_values <- input$values$diagnosis$case_detection_methods_eversmokers[,CD_method]
    }else{
      terminate_session()
      return("Unknown eligibility criteria")
    }

    input$values$global_parameters$time_horizon <- time_horizon #time_horizon + (CD_start_year-2015) + 1
      input$values$diagnosis$case_detection_start_end_yrs <- c(CD_start_year, CD_end_year)
    #}
    input$values$diagnosis$years_btw_case_detection <- yrs_btw_CD
    input$values$global_parameters$discount_cost <- discount_rate
    input$values$medication$medication_adherence <- med_adherence
    input$values$smoking$smoking_cessation_adherence <- smoking_adherence
    if(CD_method!="None"){
    input$values$diagnosis$p_case_detection[(CD_start_year+1):(CD_start_year+length(p_case_detection))] <- p_case_detection
    }
    input$values$diagnosis$p_correct_overdiagnosis <- p_correct_overdiagnosis

    input$values$diagnosis$min_cd_age <- min_age
    #input$values$diagnosis$max_cd_age <- max_age
    input$values$diagnosis$min_cd_pack_years <- min_pack_years
    input$values$diagnosis$min_cd_symptoms <- num_symptoms

    input$values$cost$cost_case_detection <- CD_values[3]*price_yr
    input$values$diagnosis$logit_p_prevalent_diagnosis_by_sex["case_detection.None",] <- CD_values[1]
    input$values$diagnosis$logit_p_diagnosis_by_sex["case_detection.None",] <- CD_values[1]
    input$values$diagnosis$logit_p_overdiagnosis_by_sex["case_detection.None",] <- CD_values[2]

    input$values$cost$bg_cost_by_stage <- input$values$cost$bg_cost_by_stage*price_yr
    input$values$cost$cost_smoking_cessation <- input$values$cost$cost_smoking_cessation*price_yr
    input$values$cost$exac_dcost <- input$values$cost$exac_dcost*price_yr
    input$values$cost$cost_outpatient_diagnosis <- input$values$cost$cost_outpatient_diagnosis*price_yr
    input$values$cost$cost_gp_visit <- input$values$cost$cost_gp_visit*price_yr
    input$values$medication$medication_costs <- input$values$medication$medication_costs*price_yr

    set.seed(445) #333
    run(input = input$values)

    output <- Cget_output()
    output_ex <- Cget_output_ex()

    terminate_session()


    # number alive
    base <- data.frame(year=1:(time_horizon),
                       criteria=eligibility_criteria,
                       CD_method=CD_method,
                       alive=rowSums(output_ex$n_alive_by_ctime_sex),
                       sex=output_ex$n_alive_by_ctime_sex[,2], # is this male or female???
                       smoke=output_ex$n_smoking_status_by_ctime[,2]
    )

    # number with COPD and diagnosed
    diags <- data.frame(copd=rowSums(output_ex$n_COPD_by_ctime_severity[,2:5]),
                        copd_sev=output_ex$n_COPD_by_ctime_severity[,4],
                        diags_true=rowSums(output_ex$n_Diagnosed_by_ctime_severity[,2:5]), # diagnosed here is true diagnosed only
                        diags_false=rowSums(output_ex$n_Overdiagnosed_by_ctime_sex),
                        diags_total=rowSums(output_ex$n_Diagnosed_by_ctime_severity[,2:5])+rowSums(output_ex$n_Overdiagnosed_by_ctime_sex)
    )

    # health outcomes
    healthOC <- data.frame(exacs=rowSums(output_ex$n_exac_by_ctime_severity),
                           exacs_mild=output_ex$n_exac_by_ctime_severity[,1],
                           exacs_mod=output_ex$n_exac_by_ctime_severity[,2],
                           exacs_sev=output_ex$n_exac_by_ctime_severity[,3],
                           exacs_vsev=output_ex$n_exac_by_ctime_severity[,4],
                           deaths=rowSums(output_ex$n_exac_death_by_ctime_severity),
                           NRT=output_ex$n_smoking_cessation_by_ctime)

    # number of case detections
    case_detection <- data.frame(case_detection=rowSums(output_ex$n_case_detection_by_ctime),
                                 CD_true_pos=output_ex$n_case_detection_by_ctime[,3],
                                 CD_false_pos=output_ex$n_case_detection_by_ctime[,2])

    # costs
    costs <- output_ex$annual_cost_ctime

    hosps <- output_ex$n_exac_by_ctime_severity[,3:4]
    hosps_cost <- input$values$cost$exac_dcost[3:4]
    hosps_cost_yr <- rowSums(t(c(hosps_cost)*t(hosps)))

    copd <- output_ex$cumul_time_by_ctime_GOLD[,2:5] #output_ex$n_COPD_by_ctime_severity[,2:5] # column 1 is gold grade 0 i.e. no copd
    main_cost <- input$values$cost$bg_cost_by_stage[2:5]
    copd_cost_yr <- rowSums(t(c(main_cost)*t(copd)))

    caseds <- output_ex$n_case_detection_by_ctime
    caseds_cost <- c(input$values$cost$cost_case_detection,
                     input$values$cost$cost_case_detection+input$values$cost$cost_outpatient_diagnosis,
                     input$values$cost$cost_case_detection+input$values$cost$cost_outpatient_diagnosis)
    caseds_cost_yr <- rowSums(t(c(caseds_cost)*t(caseds)))

    medyrs <- output_ex$medication_time_by_ctime_class[,1:4]
    medyrs_combos <- data.frame(SABA=medyrs[,1],
                                LAMA=medyrs[,3]-medyrs[,2],
                                LAMA_LABA=medyrs[,2]-medyrs[,4],
                                ICS_LAMA_LABA=medyrs[,4])
    meds_cost <- input$values$medication$medication_costs[c(2,5,7,15)]
    meds_cost_yr <- rowSums(t(c(meds_cost)*t(medyrs_combos))) + 
      output_ex$n_smoking_cessation_by_ctime*input$values$cost$cost_smoking_cessation

    costs_subcs <- data.frame(cost_total=costs,
                              cost_case_detection=caseds_cost_yr,
                              cost_treat=meds_cost_yr,
                              cost_hosp=hosps_cost_yr,
                              cost_maint=copd_cost_yr)

    results <- cbind(base,diags,healthOC,case_detection,costs_subcs)
    
    
    
    # overall results
    overall <- data.frame(n_agents=output_ex$n_agents_CD,
                          n_diagnosed=output_ex$n_diagnosed_true_CD,
                          n_CD_eligible=output_ex$n_case_detection_eligible)
    
    
    
    return(list(overall=overall,results=results))

    }
  



  # * BIA table - compare two scenarios -------------------------------------
  
  bia_table <- function(table,base_scenario,alt_scenario){
    
    base_table <- table %>%
      filter(scenario==base_scenario) %>%
      mutate(cost_case_detection_time=case_detection*11.91, .after=cost_case_detection) %>% 
      mutate(cost_case_detection_use=cost_case_detection-cost_case_detection_time, .after=cost_case_detection_time) %>% 
      select(year,scenario,criteria,CD_method,cost_total:cost_maint) %>% 
      mutate(cost_other=cost_total-cost_case_detection-cost_hosp-cost_treat)
      
    
    alt_table <- table %>%
      filter(scenario==alt_scenario) %>%
      mutate(cost_case_detection_time=case_detection*11.91, .after=cost_case_detection) %>% 
      mutate(cost_case_detection_use=cost_case_detection-cost_case_detection_time, .after=cost_case_detection_time) %>% 
      select(year,scenario,criteria,CD_method,cost_total:cost_maint) %>% 
      mutate(cost_other=cost_total-cost_case_detection-cost_hosp-cost_treat)
    
    bia_table <- data.frame(year=0:length(p_case_detection),
                            scenario=alt_scenario,
                            criteria=alt_table$criteria[1],
                            CD_method=alt_table$CD_method[1],
                            bia_total=base_table$cost_total-alt_table$cost_total,
                            bia_case_detection=base_table$cost_case_detection-alt_table$cost_case_detection,
                            bia_treat=base_table$cost_treat-alt_table$cost_treat,
                            bia_hosp=base_table$cost_hosp-alt_table$cost_hosp,
                            bia_maint=base_table$cost_maint-alt_table$cost_maint,
                            bia_other=base_table$cost_other-alt_table$cost_other)
    
    table <- bind_rows(
      base_table %>%
        pivot_longer(cols=cost_total:cost_other,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
      ,
      alt_table %>%
        pivot_longer(cols=cost_total:cost_other,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
      ,
      bia_table %>%
        pivot_longer(cols=bia_total:bia_other,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
    )
    
    return(table)
    
  }








  # * BIA per COPD patient table - compare two scenarios --------------------
  
  bia_table_pp <- function(table,base_scenario,alt_scenario){
    
    base_table <- table %>%
      filter(scenario==base_scenario) %>%
      select(year,scenario,criteria,CD_method,cost_total_pp:cost_maint_pp)
    
    alt_table <- table %>%
      filter(scenario==alt_scenario) %>%
      select(year,scenario,criteria,CD_method,cost_total_pp:cost_maint_pp)
    
    bia_table <- data.frame(year=0:length(p_case_detection),
                            scenario=alt_scenario,
                            criteria=alt_table$criteria[1],
                            CD_method=alt_table$CD_method[1],
                            bia_total_pp=base_table$cost_total_pp-alt_table$cost_total_pp,
                            bia_case_detection_pp=base_table$cost_case_detection_pp-alt_table$cost_case_detection_pp,
                            bia_treat_pp=base_table$cost_treat_pp-alt_table$cost_treat_pp,
                            bia_hosp_pp=base_table$cost_hosp_pp-alt_table$cost_hosp_pp,
                            bia_maint_pp=base_table$cost_maint_pp-alt_table$cost_maint_pp)
    
    table <- bind_rows(
      base_table %>%
        pivot_longer(cols=cost_total_pp:cost_maint_pp,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
      ,
      alt_table %>%
        pivot_longer(cols=cost_total_pp:cost_maint_pp,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
      ,
      bia_table %>%
        pivot_longer(cols=bia_total_pp:bia_maint_pp,names_to="cost_group",values_to="CAD") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=CAD)
    )
    
    return(table)
    
  }





  ho_table <- function(table,base_scenario,alt_scenario){
    
    #table <- all_results ; base_scenario <- "s10" ; alt_scenario <- "s1a"
    
    base_table <- table %>%
      filter(scenario==base_scenario) %>%
      select(year,scenario,criteria,CD_method,exacs:exacs_vsev)
    
    alt_table <- table %>%
      filter(scenario==alt_scenario) %>%
      select(year,scenario,criteria,CD_method,exacs:exacs_vsev)
    
    bia_table <- data.frame(year=0:length(p_case_detection),
                            scenario=alt_scenario,
                            criteria=alt_table$criteria[1],
                            CD_method=alt_table$CD_method[1],
                            exacs_diff=base_table$exacs-alt_table$exacs,
                            exacs_mild_diff=base_table$exacs_mild-alt_table$exacs_mild,
                            exacs_mod_diff=base_table$exacs_mod-alt_table$exacs_mod,
                            exacs_sev_diff=base_table$exacs_sev-alt_table$exacs_sev,
                            exacs_vsev_diff=base_table$exacs_vsev-alt_table$exacs_vsev)
    
    table <- bind_rows(
      base_table %>%
        pivot_longer(cols=exacs:exacs_vsev,names_to="ho_group",values_to="count") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=count)
      ,
      alt_table %>%
        pivot_longer(cols=exacs:exacs_vsev,names_to="ho_group",values_to="count") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=count)
      ,
      bia_table %>%
        pivot_longer(cols=exacs_diff:exacs_vsev_diff,names_to="ho_group",values_to="count") %>%
        pivot_wider(names_from=year,names_prefix="year_",values_from=count)
    )
    
    return(table)
    
  }

```



```{r function, echo=FALSE}

bia_all_results <- function(data){
  
  
  # overall output
  s10o <- data$s10$overall %>% mutate(scenario="s10") %>% relocate(scenario)
  s1ao <- data$s1a$overall %>% mutate(scenario="s1a") %>% relocate(scenario)
  s1bo <- data$s1b$overall %>% mutate(scenario="s1b") %>% relocate(scenario)
  s1co <- data$s1c$overall %>% mutate(scenario="s1c") %>% relocate(scenario)
  s2ao <- data$s2a$overall %>% mutate(scenario="s2a") %>% relocate(scenario)
  s3ao <- data$s3a$overall %>% mutate(scenario="s3a") %>% relocate(scenario)
  s3bo <- data$s3b$overall %>% mutate(scenario="s3b") %>% relocate(scenario)
  s3co <- data$s3c$overall %>% mutate(scenario="s3c") %>% relocate(scenario)
  s3do <- data$s3d$overall %>% mutate(scenario="s3d") %>% relocate(scenario)
  
  all_overall <- bind_rows(s10o,s1ao,s1bo,s1co,s2ao,s3ao,s3bo,s3co,s3do) # combine
  
  
  
  # set baseline year and case detection years
  baseline_yr <- CD_start_year+1-1
  CD_yrs <- (CD_start_year+1):(CD_start_year+length(p_case_detection))
  
  # year-by-year results
  s10 <- data$s10$results %>% mutate(scenario="s10", .after=year)
  s1a <- data$s1a$results %>% mutate(scenario="s1a", .after=year)
  s1b <- data$s1b$results %>% mutate(scenario="s1b", .after=year)
  s1c <- data$s1c$results %>% mutate(scenario="s1c", .after=year)
  
  #s20 <- s20 %>% mutate(scenario="s20", .after=year)
  s2a <- data$s2a$results %>% mutate(scenario="s2a", .after=year)
  
  #s30 <- s30 %>% mutate(scenario="s30", .after=year)
  s3a <- data$s3a$results %>% mutate(scenario="s3a", .after=year)
  s3b <- data$s3b$results %>% mutate(scenario="s3b", .after=year)
  s3c <- data$s3c$results %>% mutate(scenario="s3c", .after=year)
  s3d <- data$s3d$results %>% mutate(scenario="s3d", .after=year)
  
  
  # combine all year-by-year results
  all_results <- bind_rows(s10,s1a,s1b,s1c,s2a,s3a,s3b,s3c,s3d) %>% 
    filter(year %in% c(baseline_yr,CD_yrs)) %>% # remove unnecessary data
    mutate(year=year-baseline_yr) %>% # renumber so baseline year = 0 then 1:5 case detection years
    mutate(copd_prev=copd/alive*100, .after=copd) %>%
    mutate(diags_true_prev=diags_true/alive*100, .after=diags_true) %>%
    mutate(diags_false_prev=diags_false/(alive-copd)*100, .after=diags_false) %>%
    mutate(diags_total_prev=diags_total/alive*100, .after=diags_total) %>%
    mutate(cost_total_pp=cost_total/alive) %>%
    mutate(cost_case_detection_pp=cost_case_detection/alive) %>%
    mutate(cost_treat_pp=cost_treat/alive) %>%
    mutate(cost_hosp_pp=cost_hosp/alive) %>%
    mutate(cost_maint_pp=cost_maint/alive)
  
  
  baseline_avg <- all_results %>%
    filter(year==0) %>% 
    select(-year) %>% 
    summarize(alive=mean(alive),
              sex=mean(sex),
              smoke=mean(smoke),
              copd=mean(copd),
              copd_prev=mean(copd_prev),
              copd_sev=mean(copd_sev),
              diags_true=mean(diags_true),
              diags_true_prev=mean(diags_true_prev),
              diags_false=mean(diags_false),
              diags_false_prev=mean(diags_false_prev),
              diags_total=mean(diags_total),
              diags_total_prev=mean(diags_total_prev),
              exacs=mean(exacs),
              exacs_mild=mean(exacs_mild),
              exacs_mod=mean(exacs_mod),
              exacs_sev=mean(exacs_sev),
              exacs_vsev=mean(exacs_vsev),
              deaths=mean(deaths),
              case_detection=0,
              CD_true_pos=0,
              CD_false_pos=0,
              cost_total=mean(cost_total),
              cost_case_detection=0,
              cost_treat=mean(cost_treat),
              cost_hosp=mean(cost_hosp),
              cost_maint=mean(cost_maint),
              cost_total_pp=mean(cost_total_pp),
              cost_case_detection_pp=0,
              cost_treat_pp=mean(cost_treat_pp),
              cost_hosp_pp=mean(cost_hosp_pp),
              cost_maint_pp=mean(cost_maint_pp)
              )


  
  
  overall <- all_overall %>% 
    inner_join(
      all_results %>% 
        group_by(scenario) %>% 
        summarize(case_detection=sum(case_detection),
                  true_positive=sum(CD_true_pos),
                  false_positive=sum(CD_false_pos),
                  exacs=sum(exacs)),
      by="scenario"
    ) %>% 
    mutate(percent_pop_CD=case_detection/n_agents*100, .after=case_detection) %>% 
    mutate(percent_eligible_CD=case_detection/n_CD_eligible*100, .after=percent_pop_CD) %>%   
    mutate(percent_eligible=n_CD_eligible/n_agents*100, .after=n_CD_eligible) %>% 
    mutate(true_positive_rate=true_positive/case_detection*100, .after=true_positive) %>% 
    mutate(false_positive_rate=false_positive/case_detection*100, .after=false_positive)
  
  
  
  # run BIA function
  bia_s10_s1a <- bia_table(all_results,"s10","s1a")
  bia_s10_s1b <- bia_table(all_results,"s10","s1b")
  bia_s10_s1c <- bia_table(all_results,"s10","s1c")
  bia_s10_s2a <- bia_table(all_results,"s10","s2a")
  bia_s10_s3a <- bia_table(all_results,"s10","s3a")
  bia_s10_s3b <- bia_table(all_results,"s10","s3b")
  bia_s10_s3c <- bia_table(all_results,"s10","s3c")
  bia_s10_s3d <- bia_table(all_results,"s10","s3d")
  
  bia_all_long <- bind_rows(bia_s10_s1a,
                          bia_s10_s1b,
                          bia_s10_s1c,
                          bia_s10_s2a,
                          bia_s10_s3a,
                          bia_s10_s3b,
                          bia_s10_s3c,
                          bia_s10_s3d) %>% 
  distinct() %>% 
  pivot_longer(cols=year_0:year_5,names_to="year",values_to="CAD") %>% 
  mutate(year=fct_recode(year,"2021"="year_0","2022"="year_1","2023"="year_2","2024"="year_3","2025"="year_4","2026"="year_5"))
  
  
  # final desired output
  bia_total <- bia_all_long %>% 
    filter(year!="2021") %>% 
    group_by(scenario,cost_group) %>% 
    summarize(total_CAD=sum(CAD)) %>% 
    pivot_wider(names_from=scenario,values_from=total_CAD) 

  
  ho_s10_s1a <- ho_table(all_results,"s10","s1a")
  ho_s10_s1b <- ho_table(all_results,"s10","s1b")
  ho_s10_s1c <- ho_table(all_results,"s10","s1c")
  ho_s10_s2a <- ho_table(all_results,"s10","s2a")
  ho_s10_s3a <- ho_table(all_results,"s10","s3a")
  ho_s10_s3b <- ho_table(all_results,"s10","s3b")
  ho_s10_s3c <- ho_table(all_results,"s10","s3c")
  ho_s10_s3d <- ho_table(all_results,"s10","s3d")

  ho_total <- bind_rows(ho_s10_s1a,
                          ho_s10_s1b,
                          ho_s10_s1c,
                          ho_s10_s2a,
                          ho_s10_s3a,
                          ho_s10_s3b,
                          ho_s10_s3c,
                          ho_s10_s3d) %>% 
    distinct()
  
  
  
  return(list(overall=overall,bia_total=bia_total,ho_total=ho_total))
  
}



```




```{r run function, echo=FALSE, message=FALSE}


SA_base <- bia_all_results(data=readRDS("results_base445_resubmit.Rda"))


SA_MA03 <- bia_all_results(data=readRDS("results_MA03445_resubmit.Rda"))


SA_MA05 <- bia_all_results(data=readRDS("results_MA05445_resubmit.Rda"))


SA_NRT <- bia_all_results(data=readRDS("results_NRT445_resubmit.Rda"))


SA_CDUlow <- bia_all_results(data=readRDS("results_CDUlow445_resubmit.Rda"))


#SA_CDUmed <- bia_all_results(data=readRDS("results_CDUmed.Rda"))


SA_CDUhigh <- bia_all_results(data=readRDS("results_CDUhigh445_resubmit.Rda"))




```




```{r plot of total BIA, echo=FALSE}

bi_SA_base <- SA_base$bia_total %>% mutate(case="base", .before=cost_group)
bi_SA_MA03 <- SA_MA03$bia_total %>% mutate(case="MA03", .before=cost_group)
bi_SA_MA05 <- SA_MA05$bia_total %>% mutate(case="MA05", .before=cost_group)
bi_SA_NRT <- SA_NRT$bia_total %>% mutate(case="NRT", .before=cost_group)
bi_SA_CDUlow <- SA_CDUlow$bia_total %>% mutate(case="CDUlow", .before=cost_group)
#bi_SA_CDUmed <- SA_CDUmed$bia_total %>% mutate(case="CDUmed", .before=cost_group)
bi_SA_CDUhigh <- SA_CDUhigh$bia_total %>% mutate(case="CDUhigh", .before=cost_group)


bia_SA_combine <- bind_rows(bi_SA_base, bi_SA_NRT, bi_SA_MA03, bi_SA_MA05, bi_SA_CDUlow, bi_SA_CDUhigh) %>%
  pivot_longer(cols=s10:s3d, names_to="scenario",values_to="CAD") %>% 
  mutate(case=factor(case,levels=c("CDUlow","CDUhigh","base","NRT","MA05","MA03"))) %>%  
  mutate(case=fct_recode(case,"CDU low"="CDUlow","CDU high"="CDUhigh","Reference"="base","No NRT"="NRT","50% MA"="MA05","30% MA"="MA03")) %>%  
  mutate(scenario=fct_recode(scenario,"S10"="s10","S1a"="s1a","S1b"="s1b","S1c"="s1c","S2a"="s2a","S3a"="s3a","S3b"="s3b","S3c"="s3c","S3d"="s3d")) %>%
  mutate(label=if_else(case=="30% MA",as.character(scenario),NA_character_))



specVals <- levels(bia_SA_combine$case)
bia_SA_combine$case <- as.numeric(bia_SA_combine$case)

p1 <- ggplot(bia_SA_combine %>% filter(cost_group=="bia_total" & scenario!="S10"),
             aes(x=case, y=-CAD/1000000, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  ylab("Total costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  scale_x_continuous(expand=c(0.01,0.01),
                   limits=c(min(bia_SA_combine$case),max(bia_SA_combine$case)+0.2),
                   breaks=(min(bia_SA_combine$case)):(max(bia_SA_combine$case)+1), 
                   labels=c(specVals,'')) +
  #scale_x_discrete(expand=c(0.01,0.01)) +
  scale_y_continuous(breaks=seq(0,610,100), expand=c(0.02,0.02)) +
  geom_vline(xintercept=3, linetype="dashed", color = "darkgrey") +
  theme_bw() +
  theme(legend.position="none",axis.text.x=element_text(angle=45,hjust=1,vjust=1)) +
  geom_text_repel(aes(label=label),
                  nudge_x=0.2,
                  min.segment.length=Inf,
                  direction="y",
                  hjust="left")

p2 <- ggplot(bia_SA_combine %>% filter(cost_group=="bia_case_detection" & scenario!="S10"),
             aes(x=case, y=-CAD/1000000, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  ylab("Case detection costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  scale_x_continuous(expand=c(0.01,0.01),
                     limits=c(min(bia_SA_combine$case),max(bia_SA_combine$case)+0.5),
                     breaks=(min(bia_SA_combine$case)):(max(bia_SA_combine$case)+1), 
                     labels=c(specVals,'')) +
  scale_y_continuous(breaks=seq(0,610,100),expand=c(0.02,0.02)) +
  geom_vline(xintercept=3, linetype="dashed", color = "darkgrey") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1),
        legend.position = "none") +
  geom_text_repel(aes(label=label),
                  nudge_x=0.2,
                  min.segment.length=Inf,
                  direction="y",
                  size=3)

p3 <- ggplot(bia_SA_combine %>% filter(cost_group=="bia_treat" & scenario!="S10"),
             aes(x=case, y=-CAD/1000000, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_y_continuous(breaks=seq(0,100,25),expand=c(0.02,0.02)) +
  ylab("Treatment costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  scale_x_continuous(expand=c(0.01,0.01),
                     limits=c(min(bia_SA_combine$case),max(bia_SA_combine$case)+0.5),
                     breaks=(min(bia_SA_combine$case)):(max(bia_SA_combine$case)+1), 
                     labels=c(specVals,'')) +
  geom_vline(xintercept=3, linetype="dashed", color = "darkgrey") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1),
        legend.position = "none") +
  geom_text_repel(aes(label=label),
                  nudge_x=0.2,
                  min.segment.length=Inf,
                  direction="y",
                  size=3)

p4 <- ggplot(bia_SA_combine %>% filter(cost_group=="bia_hosp" & scenario!="S10"),
             aes(x=case, y=-CAD/1000000, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_y_continuous(expand=c(0.02,0.02)) +
  scale_x_continuous(expand=c(0.01,0.01),
                     limits=c(min(bia_SA_combine$case),max(bia_SA_combine$case)+0.5),
                     breaks=(min(bia_SA_combine$case)):(max(bia_SA_combine$case)+1), 
                     labels=c(specVals,'')) +
  ylab("Hospitalisation costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  geom_vline(xintercept=3, linetype="dashed", color = "darkgrey") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1),
        legend.position = "none") +
  geom_text_repel(aes(label=label),
                  nudge_x=0.2,
                  min.segment.length=Inf,
                  direction="y",
                  size=3)

p5 <- ggplot(bia_SA_combine %>% filter(cost_group=="bia_other" & scenario!="S10"),
             aes(x=case, y=-CAD/1000000, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_y_continuous(expand=c(0.02,0.02)) +
  scale_x_continuous(expand=c(0.01,0.01),
                     limits=c(min(bia_SA_combine$case),max(bia_SA_combine$case)+0.5),
                     breaks=(min(bia_SA_combine$case)):(max(bia_SA_combine$case)+1), 
                     labels=c(specVals,'')) +
  ylab("Outpatient care costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  geom_vline(xintercept=3, linetype="dashed", color = "darkgrey") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1),
        legend.position = "none") +
  geom_text_repel(aes(label=label),
                  nudge_x=0.2,
                  min.segment.length=Inf,
                  direction="y",
                  size=3)




p6 <- ggplot(bia_SA_combine %>% filter(cost_group=="cost_total"),
             aes(x=case, y=CAD/1000000, group=scenario, col=scenario)) +
  #scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Total cost (million CADs)") +
  geom_point() +
  geom_line() +
  theme_bw()

p7 <- ggplot(bia_SA_combine %>% filter(cost_group=="cost_case_detection"),
             aes(x=case, y=CAD/1000000, group=scenario, col=scenario)) +
  #scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Case detection cost (million CADs)") +
  geom_point() +
  geom_line() +
  theme_bw()

p8 <- ggplot(bia_SA_combine %>% filter(cost_group=="cost_treat"),
             aes(x=case, y=CAD/1000000, group=scenario, col=scenario)) +
  #scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Treatment cost (million CADs)") +
  geom_point() +
  geom_line() +
  theme_bw()

p9 <- ggplot(bia_SA_combine %>% filter(cost_group=="cost_hosp"),
             aes(x=case, y=CAD/1000000, group=scenario, col=scenario)) +
  #scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Hospitalisation cost (million CADs)") +
  geom_point() +
  geom_line() +
  theme_bw()



ggarrange(p1,
          ggarrange(p2,p3,p4,p5,ncol=2,nrow=2),
          nrow=2
)

#ggsave("SAresubmit.tiff",width=6000,height=8400,units="px",dpi=600)


#ggarrange(p5,p6,p7,p8,ncol=2,nrow=2,common.legend=TRUE,legend="bottom")
#ggsave("test.tiff",width=6000,height=8400,units="px",dpi=600)


# ggplot(bia_SA_combine %>% filter(cost_group=="bia_total" & scenario!="S10"),
#        aes(x=case, y=CAD/1000000, fill=scenario)) +
#   ylab("Total budget impact (million CADs)") +
#   geom_bar(stat="identity", position=position_dodge()) +
#   coord_flip() +
#   theme_bw()




```


```{r Upper age limit, echo=FALSE, message=FALSE}

SA_base <- bia_all_results(data=readRDS("results_base445_resubmit.Rda"))

SA_75 <- bia_all_results(data=readRDS("results_maxage445_resubmit.Rda"))

#SA_85 <- bia_all_results(data=readRDS("results_under85_fixsim.Rda"))




bi_SA_base <- SA_base$bia_total %>% mutate(case="Reference", .before=cost_group)
bi_SA_75 <- SA_75$bia_total %>% mutate(case="U75", .before=cost_group)
#bi_SA_85 <- SA_85$bia_total %>% mutate(case="U85", .before=cost_group)


bia_SA_combine <- bind_rows(bi_SA_base, bi_SA_75) %>%
  pivot_longer(cols=s10:s3d, names_to="scenario",values_to="CAD") %>% 
  mutate(case=factor(case,levels=c("Reference","U75"))) %>%  
  #mutate(case=fct_recode(case,"Reference"="base","U75"="U75")) %>%  
  mutate(scenario=fct_recode(scenario,"S10"="s10","S1a"="s1a","S1b"="s1b","S1c"="s1c","S2a"="s2a","S3a"="s3a","S3b"="s3b","S3c"="s3c","S3d"="s3d")) %>%
  mutate(label=if_else(case=="U75",as.character(scenario),NA_character_))





specVals <- levels(bia_SA_combine$case)
bia_SA_combine$case <- as.numeric(bia_SA_combine$case)

p1 <- ggplot(bia_SA_combine %>% filter(cost_group=="bia_total" & scenario!="S10"),
             aes(x=case, y=-CAD/1000000, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  ylab("Total costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  scale_x_continuous(expand=c(0.01,0.01),
                   limits=c(min(bia_SA_combine$case),max(bia_SA_combine$case)+0.05),
                   breaks=(min(bia_SA_combine$case)):(max(bia_SA_combine$case)+1), 
                   labels=c(specVals,'')) +
  #scale_x_discrete(expand=c(0.01,0.01)) +
  scale_y_continuous(breaks=seq(0,610,100), expand=c(0.02,0.02)) +
  geom_vline(xintercept=3, linetype="dashed", color = "darkgrey") +
  theme_bw() +
  theme(legend.position="none",axis.text.x=element_text(angle=45,hjust=1,vjust=1)) +
  geom_text_repel(aes(label=label),
                  nudge_x=0.2,
                  min.segment.length=Inf,
                  direction="y",
                  hjust="left")

p2 <- ggplot(bia_SA_combine %>% filter(cost_group=="bia_case_detection" & scenario!="S10"),
             aes(x=case, y=-CAD/1000000, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  ylab("Case detection costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  scale_x_continuous(expand=c(0.01,0.01),
                     limits=c(min(bia_SA_combine$case),max(bia_SA_combine$case)+0.075),
                     breaks=(min(bia_SA_combine$case)):(max(bia_SA_combine$case)+1), 
                     labels=c(specVals,'')) +
  scale_y_continuous(breaks=seq(0,610,100),expand=c(0.02,0.02)) +
  geom_vline(xintercept=3, linetype="dashed", color = "darkgrey") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1),
        legend.position = "none") +
  geom_text_repel(aes(label=label),
                  nudge_x=0.2,
                  min.segment.length=Inf,
                  direction="y",
                  size=3)

p3 <- ggplot(bia_SA_combine %>% filter(cost_group=="bia_treat" & scenario!="S10"),
             aes(x=case, y=-CAD/1000000, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_y_continuous(breaks=seq(0,100,25),expand=c(0.02,0.02)) +
  ylab("Treatment costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  scale_x_continuous(expand=c(0.01,0.01),
                     limits=c(min(bia_SA_combine$case),max(bia_SA_combine$case)+0.075),
                     breaks=(min(bia_SA_combine$case)):(max(bia_SA_combine$case)+1), 
                     labels=c(specVals,'')) +
  geom_vline(xintercept=3, linetype="dashed", color = "darkgrey") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1),
        legend.position = "none") +
  geom_text_repel(aes(label=label),
                  nudge_x=0.2,
                  min.segment.length=Inf,
                  direction="y",
                  size=3)

p4 <- ggplot(bia_SA_combine %>% filter(cost_group=="bia_hosp" & scenario!="S10"),
             aes(x=case, y=-CAD/1000000, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_y_continuous(expand=c(0.02,0.02)) +
  scale_x_continuous(expand=c(0.01,0.01),
                     limits=c(min(bia_SA_combine$case),max(bia_SA_combine$case)+0.075),
                     breaks=(min(bia_SA_combine$case)):(max(bia_SA_combine$case)+1), 
                     labels=c(specVals,'')) +
  ylab("Hospitalisation costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  geom_vline(xintercept=3, linetype="dashed", color = "darkgrey") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1),
        legend.position = "none") +
  geom_text_repel(aes(label=label),
                  nudge_x=0.2,
                  min.segment.length=Inf,
                  direction="y",
                  size=3)

p5 <- ggplot(bia_SA_combine %>% filter(cost_group=="bia_other" & scenario!="S10"),
             aes(x=case, y=-CAD/1000000, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  scale_y_continuous(expand=c(0.02,0.02)) +
  scale_x_continuous(expand=c(0.01,0.01),
                     limits=c(min(bia_SA_combine$case),max(bia_SA_combine$case)+0.075),
                     breaks=(min(bia_SA_combine$case)):(max(bia_SA_combine$case)+1), 
                     labels=c(specVals,'')) +
  ylab("Outpatient care costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  geom_vline(xintercept=3, linetype="dashed", color = "darkgrey") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1),
        legend.position = "none") +
  geom_text_repel(aes(label=label),
                  nudge_x=0.2,
                  min.segment.length=Inf,
                  direction="y",
                  size=3)



ggarrange(p1,
          ggarrange(p2,p3,p4,p5,ncol=2,nrow=2),
          nrow=2
)


#ggsave("ageSAresubmit.tiff",width=6000,height=8400,units="px",dpi=600)



```




```{r ISPOR plot, echo=FALSE, message=FALSE}


ggplot(bia_SA_combine %>% filter(cost_group=="bia_total" & scenario!="S10"),
             aes(x=case, y=-CAD/1000000, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9"), name="Scenario") +
  ylab("Total costs (million $)") + xlab("") +
  geom_point() +
  geom_line() +
  scale_x_discrete(expand=c(0.01,0.01)) +
  scale_y_continuous(breaks=seq(0,610,100), expand=c(0.02,0.02)) +
  geom_vline(xintercept="Reference", linetype="dashed", color = "darkgrey") +
  theme_bw() +
  theme(legend.position="right",
        axis.text.x=element_text(angle=45,hjust=1,vjust=1,size=16),
        axis.text.y=element_text(size=16),
        axis.title=element_text(size=18),
        legend.text=element_text(size=16),legend.title=element_text(size=16),
        legend.spacing.y = unit(0.5, 'cm')) +
  guides(colour = guide_legend(ncol = 1, byrow=TRUE)) 

ggsave("test3.tiff",width=7000,height=5000,units="px",dpi=600)



```



```{r health outcomes, echo=FALSE, message=FALSE}

# exacerbations by severity
sev_SA_combine <- bind_rows(
  
                            SA_base$ho_total %>% 
                            mutate(case="base", .after=scenario) %>% 
                            pivot_longer(cols=year_0:year_5, names_to="year", values_to="count") %>% 
                            filter(year!="year_0") %>% 
                            group_by(case, scenario, ho_group) %>% 
                            summarize(count=sum(count)),
                            
                            SA_MA03$ho_total %>% 
                            mutate(case="MA03", .after=scenario) %>% 
                            pivot_longer(cols=year_0:year_5, names_to="year", values_to="count") %>% 
                            filter(year!="year_0") %>% 
                            group_by(case, scenario, ho_group) %>% 
                            summarize(count=sum(count)),
                            
                            SA_MA05$ho_total %>% 
                            mutate(case="MA05", .after=scenario) %>% 
                            pivot_longer(cols=year_0:year_5, names_to="year", values_to="count") %>% 
                            filter(year!="year_0") %>% 
                            group_by(case, scenario, ho_group) %>% 
                            summarize(count=sum(count)),
                            
                            SA_NRT$ho_total %>% 
                            mutate(case="NRT", .after=scenario) %>% 
                            pivot_longer(cols=year_0:year_5, names_to="year", values_to="count") %>% 
                            filter(year!="year_0") %>% 
                            group_by(case, scenario, ho_group) %>% 
                            summarize(count=sum(count)),
                            
                            SA_CDUlow$ho_total %>% 
                            mutate(case="CDUlow", .after=scenario) %>% 
                            pivot_longer(cols=year_0:year_5, names_to="year", values_to="count") %>% 
                            filter(year!="year_0") %>% 
                            group_by(case, scenario, ho_group) %>% 
                            summarize(count=sum(count)),
                            
                            SA_CDUmed$ho_total %>% 
                            mutate(case="CDUmed", .after=scenario) %>% 
                            pivot_longer(cols=year_0:year_5, names_to="year", values_to="count") %>% 
                            filter(year!="year_0") %>% 
                            group_by(case, scenario, ho_group) %>% 
                            summarize(count=sum(count)),
                            
                            SA_CDUhigh$ho_total %>% 
                            mutate(case="CDUhigh", .after=scenario) %>% 
                            pivot_longer(cols=year_0:year_5, names_to="year", values_to="count") %>% 
                            filter(year!="year_0") %>% 
                            group_by(case, scenario, ho_group) %>% 
                            summarize(count=sum(count)),
                            
                            
                            
                            ) %>% 
  pivot_wider(names_from=ho_group,values_from=count) %>% 
  mutate(case=factor(case,levels=c("CDUlow","CDUmed","CDUhigh","base","MA05","MA03","NRT")))



p3 <- ggplot(sev_SA_combine %>% filter(scenario!="s10"),
             aes(x=case, y=exacs_diff, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Exacerbations avoided") +
  geom_point() +
  geom_line() +
  theme_bw()
p4 <- ggplot(sev_SA_combine %>% filter(scenario!="s10"),
             aes(x=case, y=exacs_mild_diff, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Mild exacerbations avoided") +
  geom_point() +
  geom_line() +
  theme_bw()
p5 <- ggplot(sev_SA_combine %>% filter(scenario!="s10"),
             aes(x=case, y=exacs_mod_diff, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Moderate exacerbations avoided") +
  geom_point() +
  geom_line() +
  theme_bw()
p6 <- ggplot(sev_SA_combine %>% filter(scenario!="s10"),
             aes(x=case, y=exacs_sev_diff, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Severe exacerbations avoided") +
  geom_point() +
  geom_line() +
  theme_bw()



p7 <- ggplot(sev_SA_combine,
             aes(x=case, y=exacs, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Exacerbations") +
  geom_point() +
  geom_line() +
  theme_bw()
p8 <- ggplot(sev_SA_combine,
             aes(x=case, y=exacs_mild, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Mild exacerbations") +
  geom_point() +
  geom_line() +
  theme_bw()
p9 <- ggplot(sev_SA_combine,
             aes(x=case, y=exacs_mod, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Moderate exacerbations") +
  geom_point() +
  geom_line() +
  theme_bw()
p10 <- ggplot(sev_SA_combine,
             aes(x=case, y=exacs_sev, group=scenario, col=scenario)) +
  scale_color_manual(values=c("#808080", "#F5594E", "#E7861B", "#95A900", "#00B81F", "#00C0B8", "#00A5FF", "#BF80FF", "#FF61C9")) +
  ylab("Severe exacerbations") +
  geom_point() +
  geom_line() +
  theme_bw()





grid.arrange(p3,p4,p5,p6,nrow=2)
grid.arrange(p7,p8,p9,p10,nrow=2)



```

